// ========== ALL 13 LESSONS DATA ========== //

const levels = {
    b2: {
        name: "B2 - Upper Intermediate",
        lessons: {
            lektion1: {
                name: "Lektion 1: Communication",
                cards: [
        { german: "ausdrücken", english: "to express" },
        { german: "ausreden", english: "finish speaking, talk out" },
        { german: "ausreden lassen", english: "to let finish" },
        { german: "ausweichen + D", english: "to evade" },
        { german: "sich einmischen", english: "to interfere" },
        { german: "gestikulieren", english: "to gesticulate" },
        { german: "hinzufügen + A (etwas) (zu + D)", english: "to add" },
        { german: "kommunizieren mit + D", english: "to communicate (with)" },
        { german: "nachfragen (bei + D)", english: "to enquire" },
        { german: "nachhaken (bei + D)", english: "to follow up" },
        { german: "überfordern + A", english: "to overchallenge" },
        { german: "unterfordern + A", english: "to underchallenge" },
        { german: "überschätzen + A", english: "to overestimate" },
        { german: "unterschätzen + A", english: "to underestimate" },
        { german: "übertreiben + A", english: "to overstate" },
        { german: "untertreiben + A", english: "to understate" },
        { german: "vermitteln + A", english: "to convey" },
        { german: "vertreten + A", english: "to represent" },
        { german: "sich abwenden (von + D)", english: "to turn away/avert" },
        { german: "abwinken", english: "wave off" },
        { german: "einleuchten + D", english: "to be clear/logical" },
        { german: "sich erschließen + D", english: "to deduce" },
        { german: "flüstern", english: "to whisper" },
        { german: "missfallen + D", english: "to dislike" },
        { german: "misstrauen + D", english: "to distrust" },
        { german: "missverstehen + A", english: "to misunderstand" },
        { german: "nachvollziehen + A", english: "to comprehend" },
        { german: "signalisieren + D + A", english: "to signal" },
        { german: "vorwerfen + D + A", english: "to reproach" },
        { german: "sich wegdrehen", english: "to turn away" },
        { german: "in die Hände klatschen", english: "to clap" },
        { german: "mit dem Kopf nicken", english: "to nod" },
        { german: "den Kopf schütteln", english: "to shake head" },
        { german: "jammern", english: "to whine" },
        { german: "das Gesicht verziehen", english: "to grimace" },
        { german: "mit den Schultern/Achseln zucken", english: "to shrug" },
        { german: "stoßen auf + A", english: "to bump into" },
        { german: "die Mehrsprachigkeit", english: "the multilingualism" },
        { german: "die Körpersprache, -n", english: "the body language" },
        { german: "die Alltagssprache, -n", english: "the everyday language" },
        { german: "die Stimmlage, -n", english: "the tone of voice" },
        { german: "der Gesprächsstoff, -e", english: "the conversation material" },
        { german: "der Spracherwerb", english: "the language acquisition" },
        { german: "der Gesichtsausdruck, -e", english: "the facial expression" },
        { german: "der Blickkontakt, -e", english: "the eye contact" },
        { german: "das Bedauern", english: "the regret" },
        { german: "das Gegenüber", english: "the counterpart" },
        { german: "akzentfrei", english: "accent-free" },
        { german: "ausführlich", english: "detailed" },
        { german: "ausweichend", english: "evasive" },
        { german: "hartnäckig", english: "persistent" },
        { german: "heftig", english: "vehement" },
        { german: "komplex", english: "complex" },
        { german: "jemandem ins Wort fallen", english: "to interrupt somebody" },
        { german: "zu Wort kommen", english: "to get a word in" },
        { german: "etwas auf dem Herzen haben", english: "to have something on one's mind" },
        { german: "reden wie ein Wasserfall", english: "to talk non-stop" },
        { german: "ganz Ohr sein", english: "to be all ears" },
        { german: "den Faden verlieren", english: "to lose the thread" },
        { german: "nur Bahnhof verstehen", english: "to understand nothing" },
        { german: "sich an den Kopf greifen/fassen", english: "to be aghast" }
    ],
},

    lektion2: { 
        name: "Lektion 2: Emotions & Relationships",
        cards: [
        // Lektion 2: Emotions & Relationships
        { german: "flirten mit + D", english: "to flirt with" },
        { german: "sich hineinversetzen", english: "to put oneself in someone's position" },
        { german: "trösten + A", english: "to comfort" },
        { german: "sich sehnen nach + D", english: "to yearn for" },
        { german: "zittern", english: "to tremble" },
        { german: "verheimlichen + A (vor + D)", english: "to conceal something (from someone)" },
        { german: "neidisch sein auf + A", english: "to be envious" },
        { german: "ermutigen", english: "to encourage" },
        { german: "ablenken + A von + D", english: "to distract (from)" },
        { german: "nerven + A", english: "to get on nerves" },
        { german: "aufmuntern + A", english: "to cheer up" },
        { german: "sich trauen, etw zu tun", english: "to dare to do something" },
        { german: "ausdrücken + A", english: "to express" },
        { german: "vernachlässigen + A", english: "to neglect" },
        { german: "ausnutzen + A", english: "to take advantage of" },
        { german: "befreundet mit + D", english: "to befriend (with)" },
        { german: "hintergehen + A", english: "to deceive" },
        { german: "übergehen + A", english: "to disregard, to skip" },
        { german: "sich auswirken auf + A", english: "to have an effect on" },
        { german: "sich beklagen über + A", english: "to complain about" },
        { german: "sich bemühen um + A", english: "to strive for" },
        { german: "sich erschrecken vor + D", english: "to be frightened of" },
        { german: "zum Ausdruck bringen + A", english: "to express" },
        { german: "in Verlegenheit bringen", english: "to embarrass" },
        { german: "unter Kontrolle bringen", english: "to bring under control" },
        { german: "ins Herz schließen + A", english: "to take into one's heart" },
        { german: "die Daumen drücken", english: "to cross one's fingers" },
        { german: "eine Entscheidung fällen", english: "to make a decision" },
        { german: "eine Ehe führen", english: "to conduct a marriage" },
        { german: "die Nase voll haben von + D", english: "to be fed up (with)" },
        { german: "ein Gespräch führen", english: "to have a conversation" },
        { german: "auf die Nerven gehen + D", english: "to get on the nerves" },
        { german: "einen Kampf führen", english: "to fight a battle" },
        { german: "Schmetterlinge im Bauch haben", english: "to have butterflies in the stomach" },
        { german: "zu Ende gehen", english: "to come to an end" },
        { german: "zu Hilfe kommen + D", english: "to come to the aid of" },
        { german: "in Erfüllung gehen", english: "to come to fulfillment" },
        { german: "vor den Kopf stoßen", english: "to affront, to offend" },
        { german: "in Tränen ausbrechen", english: "to burst into tears" },
        { german: "ein Kompliment machen + D", english: "to pay a compliment" },
        { german: "den Atem verschlagen + D", english: "to take one's breath away" },
        { german: "charmant", english: "charming" },
        { german: "verlegen", english: "embarrassed" },
        { german: "eklig", english: "disgusting" },
        { german: "entsetzlich, fürchterlich, grauenhaft, grauenvoll", english: "horrible" },
        { german: "hervorragend", english: "excellent" },
        { german: "überwältigt", english: "overwhelmed" },
        { german: "traumhaft", english: "dreamlike" },
        { german: "euphorisch", english: "euphoric" },
        { german: "die Nachbarschaft, -en", english: "the neighborhood" },
        { german: "die Verwandtschaft, -en", english: "the kinship" },
        { german: "die Eifersucht auf + A", english: "the jealousy" },
        { german: "die Emotion, -en", english: "the emotion" },
        { german: "die Sehnsucht nach + D", english: "the longing" },
        { german: "die Verlegenheit", english: "the embarrassment" },
        { german: "das Freundschaftsverhältnis, -se", english: "the friendship relationship" },
        { german: "das Liebesverhältnis, -se", english: "the love relationship" },
        { german: "der Ekel vor + D", english: "the disgust" },
        { german: "der Frust", english: "the frustration" },
        { german: "der Neid auf + A", english: "the envy" },
        { german: "der Trost", english: "the consolation" },
        { german: "der Bekanntenkreis, -e", english: "the circle of acquaintances" },
        { german: "der Familienkreis, -e", english: "the family circle" },
        { german: "das Erstaunen", english: "the astonishment" },
        { german: "das Herzklopfen", english: "the heart palpitation" }
    ],

    lektion3: [
        // Lektion 3: Passport Control & Immigration
        { german: "zurechtkommen mit + D", english: "to cope with" },
        { german: "einwandern", english: "to immigrate" },
        { german: "überstehen + A", english: "to survive" },
        { german: "sich zurechtfinden", english: "to orient oneself" },
        { german: "konfrontiert sein mit + D", english: "to be confronted with" },
        { german: "sich niederlassen", english: "to settle down" },
        { german: "identifizieren mit + D", english: "to identify with" },
        { german: "abstammen von + D", english: "to descend from" },
        { german: "sich anpassen an + A", english: "to adapt to" },
        { german: "anwerben + A", english: "to recruit" },
        { german: "anwerben + A", english: "to address" },
        { german: "aufbrechen", english: "to break open" },
        { german: "sich austauschen mit + D über + A", english: "to exchange" },
        { german: "beeindrucken + A", english: "to impress" },
        { german: "sich einleben", english: "to settle in" },
        { german: "erkunden + A", english: "to explore" },
        { german: "gehören zu + D", english: "to belong to" },
        { german: "entsprechen + D", english: "to correspond to" },
        { german: "sich ergeben", english: "to surrender" },
        { german: "gelten als + N", english: "to be considered as" },
        { german: "sich lohnen", english: "to be worthwhile" },
        { german: "sich verbeugen vor + D", english: "to bow to" },
        { german: "sich von selbst verstehen", english: "to understand oneself" },
        { german: "die Arbeitskraft, --e", english: "the workforce" },
        { german: "die Bezeichnung, --en", english: "the designation" },
        { german: "die Armut (nur Sg.)", english: "the poverty" },
        { german: "die Katastrophe, --n", english: "the catastrophe" },
        { german: "die Diskriminierung, --en", english: "the discrimination" },
        { german: "die Lebenshaltungskosten (nur Pl.)", english: "the cost of living" },
        { german: "die Minderheit, --en", english: "the minority" },
        { german: "die Nationalität, --en", english: "the nationality" },
        { german: "die (traditionelle) Küche (nur Sg.)", english: "the (traditional) cuisine" },
        { german: "die Wurzel, -n", english: "the root" },
        { german: "die (Tisch-)Sitte, -n", english: "the table manners" },
        { german: "die Vertreibung (nur Sg.)", english: "the expulsion" },
        { german: "die (Tisch-/Ess-)Manieren (nur Pl.)", english: "the (table/dining) manners" },
        { german: "die Perspektive, -n", english: "the perspective" },
        { german: "die Tracht, -en", english: "the costume" },
        { german: "die Staatsangehörigkeit, -en", english: "the nationality" },
        { german: "der/die Angehörige, -n", english: "the relative" },
        { german: "der Bürgerkrieg, -e", english: "the civil war" },
        { german: "der/die Einheimische, -n", english: "the local" },
        { german: "der Umstand, :-e", english: "the circumstance" },
        { german: "der Auswanderer, -; die Auswanderin, -nen", english: "the emigrant" },
        { german: "der Passant, -en; die Passantin, -nen", english: "the passerby" },
        { german: "der Brauch, :-e", english: "the custom" },
        { german: "der Einwanderer, -; die Einwanderin, -nen", english: "the immigrant" },
        { german: "das Einwanderungsland, -er", english: "the immigration country" },
        { german: "das Tabu, -s", english: "the taboo" },
        { german: "der Vorfahr, -en; die Vorfahrin, -nen", english: "the ancestor" },
        { german: "die (Denk-/Lebens-)Weise", english: "the way of thinking/living" },
        { german: "das Herkunftsland, -er", english: "the country of origin" },
        { german: "das Zielland, -er", english: "the destination country" },
        { german: "der Migrationshintergrund, -e", english: "the migration background" },
        { german: "der Flüchtling, -e; der/die Geflüchtete, -n", english: "the refugee" }
    ],
},

    lektion4: {
        name: "Lektion 4: Objects & Materials",
        cards: [
        // Lektion 4: Objects & Materials
        { german: "abhandenkommen", english: "to go missing" },
        { german: "sich anfühlen", english: "to feel" },
        { german: "aufkommen für + A", english: "to pay for" },
        { german: "auftreiben + A", english: "to find" },
        { german: "begleichen + A", english: "to pay" },
        { german: "entgegenkommen + D", english: "to accommodate" },
        { german: "dahinterkommen", english: "to figure out, to suss out" },
        { german: "eingestehen + A", english: "to admit" },
        { german: "erstatten + A", english: "to refund" },
        { german: "leisten + A", english: "to afford" },
        { german: "spenden + A", english: "to donate" },
        { german: "zugutekommen + D", english: "to benefit" },
        { german: "sich abnutzen", english: "to wear out" },
        { german: "absaugen + A", english: "to vacuum" },
        { german: "abstauben + A", english: "to dust" },
        { german: "abwischen + A", english: "to wipe" },
        { german: "aufbewahren + A", english: "to store" },
        { german: "aufbrauchen + A", english: "to use up" },
        { german: "aussortieren + A", english: "to sort out" },
        { german: "erstehen + A", english: "to purchase" },
        { german: "erwerben + A", english: "to acquire" },
        { german: "loswerden + A", english: "to get rid of" },
        { german: "missbrauchen + A", english: "to misuse, abuse" },
        { german: "polieren + A", english: "to polish" },
        { german: "unterbringen + A", english: "to house, to accommodate" },
        { german: "verstauen + A", english: "to stow" },
        { german: "wegschmeißen + A", english: "to throw away" },
        { german: "wischen + A", english: "to mop" },
        { german: "zerfallen", english: "to disintegrate" },
        { german: "zerschlagen + A", english: "to smash" },
        { german: "sich Mühe geben", english: "to make an effort" },
        { german: "zu Bruch gehen", english: "to break" },
        { german: "in Kauf nehmen", english: "to accept something" },
        { german: "eine Rolle spielen", english: "to play a role" },
        { german: "Gewinn erzielen/machen", english: "to earn/make a profit" },
        { german: "zur Verfügung stellen", english: "to make available" },
        { german: "Gebrauch machen von + D", english: "to make use of" },
        { german: "die Pinnwand, --e", english: "the pinboard" },
        { german: "die Säge, -n", english: "the saw" },
        { german: "die Schublade, -n", english: "the drawer" },
        { german: "die Baumwolle", english: "the cotton wool" },
        { german: "das Kuscheltier", english: "the cuddly toy" },
        { german: "das Milchprodukt", english: "the milk product" },
        { german: "das Silber (nur Sg.)", english: "the silver" },
        { german: "das Springseil, -e", english: "the skipping rope" },
        { german: "der Anspitzer, -", english: "the sharpener" },
        { german: "der Stoff", english: "the fabric" },
        { german: "der Blumentopf, --e", english: "the flower pot" },
        { german: "der Büro-/Haushalts-Artikel, -", english: "the office/household articles" },
        { german: "der Dreitagebart, --e", english: "the three-day beard" },
        { german: "der Eierbecher, -", english: "the egg cup" },
        { german: "der Impfstoff", english: "the vaccine" },
        { german: "der Radiergummi", english: "the eraser" },
        { german: "der Rohstoff, -e", english: "the raw material" },
        { german: "der Ton (nur Sg.)", english: "the clay" },
        { german: "der Schraubenzieher, -", english: "the screwdriver" },
        { german: "der Putzlappen, -", english: "the cleaning rag" },
        { german: "der Treibstoff, -e", english: "the fuel" },
        { german: "der Kork", english: "the cork" },
        { german: "der Ohrring", english: "the earring" },
        { german: "das Aluminium", english: "the aluminum" },
        { german: "das Antibiotikum", english: "the antibiotic" },
        { german: "das Arzneimittel", english: "the medicine" },
        { german: "das Besteck, -e", english: "the cutlery" },
        { german: "das Erdöl (nur Sg.)", english: "the crude oil" },
        { german: "das Getreide (nur Sg.)", english: "the grain" },
        { german: "das Kerosin", english: "the paraffin" },
        { german: "das Porzellan", english: "the porcelain" },
        { german: "einzigartig", english: "unique" },
        { german: "kratzig", english: "scratchy" },
        { german: "flauschig", english: "fluffy" },
        { german: "rau", english: "rough" },
        { german: "glitzrig", english: "slippery" },
        { german: "butterweich", english: "buttersoft" },
        { german: "klebrig", english: "sticky" },
        { german: "eiskalt", english: "ice-cold" },
        { german: "hochinteressant", english: "highly interesting" },
        { german: "brandneu", english: "brand new" },
        { german: "klitschnass", english: "soaking wet" },
        { german: "nagelneu", english: "brandnew" },
        { german: "knochentrocken", english: "bone dry" },
        { german: "riesengroß", english: "huge" },
        { german: "kochend heiß", english: "boiling hot" },
        { german: "steinhart", english: "rock hard" },
        { german: "stinknormal", english: "stinkingnormal" },
        { german: "todlangweilig", english: "deadly boring" },
        { german: "stockdunkel", english: "pitch black" },
        { german: "uralt", english: "ancient" },
        { german: "taghell", english: "as bright as day" },
        { german: "winzig klein", english: "tiny" }
    ],
},
        lektion5: {
            name: "Lektion 5: Arts & Culture",
            cards: [
        // Lektion 5: Arts & Culture
        { german: "gestalten + A", english: "to design" },
        { german: "improvisieren + A", english: "to improvise" },
        { german: "inspirieren + A", english: "to inspire" },
        { german: "interpretieren + A", english: "to interpret" },
        { german: "proben", english: "to rehearse" },
        { german: "veranstalten + A", english: "to organize" },
        { german: "wiedergeben", english: "to render" },
        { german: "ausfallen", english: "to turn out" },
        { german: "auszeichnen + A mit + D", english: "to price sth, to award" },
        { german: "abstreiten", english: "to deny" },
        { german: "basieren auf", english: "based on" },
        { german: "begehen + A", english: "to commit" },
        { german: "formulieren + A", english: "to formulate" },
        { german: "herausgeben + A", english: "to publish" },
        { german: "schildern + A", english: "describe" },
        { german: "verfassen + A", english: "to write" },
        { german: "verfilmen + A", english: "to make a film of" },
        { german: "vernehmen + A", english: "to examine" },
        { german: "verweigern + A", english: "to refuse" },
        { german: "vorlegen + A", english: "to present, to submit" },
        { german: "die Architektur (nur Sg.)", english: "the architecture" },
        { german: "die Atmosphäre, -n", english: "the atmosphere" },
        { german: "die Bildhauerei (nur Sg.)", english: "the sculpture" },
        { german: "die Bronze, -n", english: "the bronze" },
        { german: "die Geige, -n", english: "the violin" },
        { german: "die Installationskunst (Sg.)", english: "the installation art" },
        { german: "die Violine, -n", english: "the violin" },
        { german: "die Trompete, -n", english: "the trumpet" },
        { german: "die Karikatur, -en", english: "the caricature" },
        { german: "die Keramik, -en", english: "the ceramic" },
        { german: "die Ziehharmonika, -s", english: "the accordion" },
        { german: "die Anspielung, -en auf + A", english: "the allusion" },
        { german: "die Ölfarbe, das Öl (Sg.)", english: "the oil paint" },
        { german: "die Malerei, -en", english: "the painting" },
        { german: "die Pantomime (nur Sg.)", english: "the pantomime" },
        { german: "die Leinwand", english: "the canvas" },
        { german: "die Chronologie, -en", english: "the chronology" },
        { german: "die Vernehmung, -en", english: "the interrogation" },
        { german: "die Entführung, -en", english: "the abduction" },
        { german: "die Erpressung, -en", english: "the blackmail" },
        { german: "die Schilderung, -en", english: "the description" },
        { german: "die Spur, -en", english: "the track, trail" },
        { german: "die Handlung, -en", english: "the plot" },
        { german: "die Hauptfigur, -en", english: "the main character" },
        { german: "der E-Bass, --e", english: "the electric bass" },
        { german: "der Pinsel, -", english: "the brush" },
        { german: "der Marmor (nur Sg.)", english: "the marble" },
        { german: "der Kommissar, -e; die Kommissarin, -nen", english: "the commissioner" },
        { german: "der Mörder, -; die Mörderin, -nen", english: "the murderer" },
        { german: "der Tatort, -e", english: "the crime scene" },
        { german: "das Lösegeld, -er", english: "the ransom" },
        { german: "das Rauschgift, -e", english: "the drug" },
        { german: "das (Selbst-)Porträt", english: "the (self) portrait" },
        { german: "das Schlagzeug, -e", english: "the drums" },
        { german: "der/die Verdächtige, -n", english: "the suspect" },
        { german: "der Werkstoff, -e", english: "the material" },
        { german: "der Ton (nur Sg.)", english: "the sound" },
        { german: "das Akkordeon, -s", english: "the accordion" },
        { german: "das Ballett (nur Sg.)", english: "the ballet" },
        { german: "das Figuren-/Puppentheater", english: "the figure / puppet theatre" },
        { german: "das Gemälde", english: "the painting" },
        { german: "das Kunstwerk, -e", english: "the work of art" },
        { german: "das Mauerwerk (nur Sg.)", english: "the masonry" },
        { german: "das Mosaik, -e", english: "the mosaic" },
        { german: "das Musical, -s", english: "the musical" },
        { german: "chronologisch", english: "chronologically" },
        { german: "detailreich", english: "rich in detail" },
        { german: "faszinierend", english: "fascinating" },
        { german: "(un)glaubwürdig", english: "(un)credible" },
        { german: "hervorragend", english: "terrific" },
        { german: "langatmig", english: "long-winded" },
        { german: "literarisch", english: "literary" },
        { german: "meisterhaft", english: "masterly" },
        { german: "den Takt halten", english: "keep the beat" },
        { german: "aus der Sicht + G", english: "from the perspective of" },
        { german: "in Worte fassen + A", english: "express in words" }
    ],
},

    lektion6: {
        name: "Lektion 6: History & Society",
        cards: [
        // Lektion 6: History & Society
        { german: "sich ausbreiten", english: "to spread out" },
        { german: "bilden + A", english: "to build, to form" },
        { german: "erobern + A", english: "to conquer" },
        { german: "prägen + A", english: "to shape, coin" },
        { german: "spalten + A", english: "to cleave" },
        { german: "überliefern + A", english: "to hand down" },
        { german: "verbreiten + A", english: "to spread" },
        { german: "zusammensetzen aus + D", english: "to put together" },
        { german: "christianisieren + A", english: "to christianise" },
        { german: "ausbrechen", english: "to break out" },
        { german: "reformieren + A", english: "to reform" },
        { german: "sich verstärken", english: "to strengthen" },
        { german: "die Antike (nur Sg.)", english: "the ancient" },
        { german: "die Aufklärung (nur Sg.)", english: "the enlightenment" },
        { german: "die Ausbreitung (nur Sg.)", english: "the spread" },
        { german: "die (gesellschaftliche) Bewegung, -en", english: "the (social) movement" },
        { german: "die Entdeckung, -en", english: "the discovery" },
        { german: "die Epoche, -n", english: "the era" },
        { german: "die Eroberung, -en", english: "the conquest" },
        { german: "die Industrialisierung (nur Sg.)", english: "the industrialization" },
        { german: "die Kolonialzeit (nur Sg.)", english: "the colonial era" },
        { german: "die Konfession, -en", english: "the denomination" },
        { german: "die Neuzeit (nur Sg.)", english: "the modern age" },
        { german: "die Quelle, -n", english: "the origin" },
        { german: "die Reform, -en", english: "the reform" },
        { german: "die Reformation (nur Sg.)", english: "the Reformation" },
        { german: "die Blütezeit, -en", english: "the flowering period" },
        { german: "die Völkerwanderung, -en", english: "the migration of peoples" },
        { german: "die Sowjetunion (nur Sg.)", english: "the Soviet Union" },
        { german: "die Monarchie, -n", english: "the monarchy" },
        { german: "die Grundlage, -n", english: "the basis" },
        { german: "die Nachkriegszeit (nur Sg.)", english: "the postwar era" },
        { german: "die Herrscherin, -nen", english: "the ruler" },
        { german: "die (deutsche) Teilung (nur Sg.)", english: "the (German) division" },
        { german: "die Moderne (nur Sg.)", english: "the modern era" },
        { german: "die (Kolonial-/Militär-/Schreckens-) Herrschaft (nur Sg.)", english: "the (colonial/military/terror) reign" },
        { german: "das (Römische/Kaiser-/Königs-) Reich, -e", english: "the Roman/Imperial/King's Empire" },
        { german: "das Wirtschaftswunder (nur Sg.)", english: "the economic miracle" },
        { german: "das Militär (nur Sg.)", english: "the military" },
        { german: "das Gebot", english: "the commandment" },
        { german: "der Mauerfall (nur Sg.)", english: "the fall of the Berlin wall" },
        { german: "der Überfall auf + A", english: "the raid" },
        { german: "die Vernunft", english: "the reason" },
        { german: "die (deutsche) Wiedervereinigung (nur Sg.)", english: "the (German) reunification" },
        { german: "das Altgriechisch (nur Sg.)", english: "the ancient greek" },
        { german: "das Christentum (nur Sg.)", english: "the christianity" },
        { german: "das Erbe (nur Sg.)", english: "the heritage" },
        { german: "das Königreich, -e", english: "the kingdom" },
        { german: "das Latein (nur Sg.)", english: "the Latin" },
        { german: "das Mittelalter (nur Sg.)", english: "the Middle Ages" },
        { german: "das Oberhaupt, --er", english: "the head, leader" },
        { german: "das Randgebiet, -e", english: "the peripheral area" },
        { german: "der Adel (nur Sg.)", english: "the nobility" },
        { german: "der/die Adlige, -n", english: "the nobleman/woman" },
        { german: "der Bischof, --e", english: "the bishop" },
        { german: "der Nationalsozialismus (nur Sg.)", english: "the national socialism" },
        { german: "der Glaube (nur Sg.)", english: "the belief" },
        { german: "der/die Geistliche, -n", english: "the clergy" },
        { german: "der Gebrauch (nur Sg.)", english: "the use" },
        { german: "der Kaiser, -", english: "the emperor" },
        { german: "der Nationalstaat, -en", english: "the nation state" },
        { german: "der Papst, --e", english: "the pope" },
        { german: "der Stadtkern, -e", english: "the city center" },
        { german: "der Stadtstaat, -en", english: "the city state" },
        { german: "der Stand, --e", english: "the stand, the state of affairs" },
        { german: "der Übergang, --e", english: "the transition" },
        { german: "der Zerfall (nur Sg.)", english: "the disintegration" },
        { german: "der Herrscher, --", english: "the ruler" },
        { german: "archäologisch", english: "archaeological" },
        { german: "antik", english: "antique" },
        { german: "stabil", english: "stable" },
        { german: "erfolglos ≠ erfolgreich", english: "unsuccessful ≠ successful" },
        { german: "christlich", english: "christian" },
        { german: "evangelisch", english: "evangelical" },
        { german: "geistig", english: "spiritual" },
        { german: "geistlich", english: "churchly" },
        { german: "ortsansässig", english: "local" },
        { german: "römisch", english: "roman" },
        { german: "weltlich", english: "secular" },
        { german: "katholisch", english: "catholic" },
        { german: "mittelalterlich", english: "medieval" },
        { german: "vorhersehbar", english: "predictable" },
        { german: "historisch", english: "historic" },
        { german: "demokratisch", english: "democratic" },
        { german: "einen Krieg führen", english: "wage a war" },
        { german: "Einfluss nehmen", english: "exert influence" },
        { german: "Frieden schließen", english: "make peace" },
        { german: "sich etwas zum Ziel setzen", english: "to set oneself a goal" }
    ],
},

    lektion7: {
        name: "Lektion 7: Education & Career",
        cards: [
        // Lektion 7: Education & Career
        { german: "abbrechen + A", english: "to drop out" },
        { german: "abwenden + A", english: "to avert" },
        { german: "beerdigen + A", english: "to bury" },
        { german: "beibehalten + A", english: "to maintain" },
        { german: "belegen + A", english: "to attend, to sign up for" },
        { german: "einhalten + A", english: "to adhere to" },
        { german: "einreichen + A", english: "to submit" },
        { german: "sich einschreiben", english: "to enroll" },
        { german: "entnehmen + D + A", english: "to extract" },
        { german: "erbringen + A", english: "to provide" },
        { german: "sich immatrikulieren", english: "to enroll" },
        { german: "nachreichen + A", english: "to submit later" },
        { german: "nachweisen + A", english: "to prove" },
        { german: "ringen um + A", english: "to struggle, fight for" },
        { german: "vermitteln + A", english: "to convey" },
        { german: "absolvieren + A", english: "to complete" },
        { german: "ausschreiben + A", english: "to advertise" },
        { german: "bereithalten + A", english: "to have ready" },
        { german: "bewältigen + A", english: "to cope" },
        { german: "durchbringen + A", english: "to support" },
        { german: "durchgehen + A", english: "to go through" },
        { german: "durchhalten + A", english: "to keep up" },
        { german: "durchziehen + A", english: "to pull through" },
        { german: "hinbekommen + A", english: "to get it done" },
        { german: "investieren + A", english: "to invest" },
        { german: "meistern + A", english: "to master" },
        { german: "stoßen auf + A", english: "to bump into, to come across" },
        { german: "scheitern an + D", english: "to fail" },
        { german: "übernehmen + A", english: "to take over" },
        { german: "umfassen + A", english: "to include, to comprise" },
        { german: "schwinden", english: "to dwindle" },
        { german: "versagen", english: "to fail" },
        { german: "sich weiterbilden", english: "to continue to educate" },
        { german: "zustande bringen + A", english: "to achieve" },
        { german: "sich zutrauen", english: "to believe capable" },
        { german: "sich bewusst sein + G", english: "to be conscious" },
        { german: "auf die Beine stellen", english: "to get up and running" },
        { german: "eine brotlose Kunst sein", english: "to be unprofitable" },
        { german: "(Berufs-)Erfahrungen sammeln", english: "to gain (work) experience" },
        { german: "einen Beruf ergreifen", english: "to take up a profession" },
        { german: "die Absolventin, -nen", english: "the graduate" },
        { german: "die Betriebswirtschaft (nur Sg.)", english: "the business administration" },
        { german: "die Elektrotechnik (nur Sg.)", english: "the electrical engineering" },
        { german: "Jura (nur Sg.)", english: "Law" },
        { german: "die Kunstgeschichte (nur Sg.)", english: "the history of arts" },
        { german: "die Lehrveranstaltung, -en", english: "the course" },
        { german: "die Orchidee, -n", english: "the orchid" },
        { german: "die Pädagogik (nur Sg.)", english: "the pedagogy" },
        { german: "die Soziologie (nur Sg.)", english: "the sociology" },
        { german: "die Abrechnung, -en", english: "the billing" },
        { german: "die Sprachwissenschaft, -en", english: "the linguistics" },
        { german: "die Buchhalterin, -nen", english: "the accountant" },
        { german: "die Volkswirtschaft, -en", english: "the economics" },
        { german: "die Stellenanzeige, -n", english: "the job advertisement" },
        { german: "die Zulassung, -en", english: "the admission" },
        { german: "zur allgemeinen Zufriedenheit", english: "to general satisfaction" },
        { german: "der Absolvent, -en", english: "the graduate" },
        { german: "der Studiengang, --e", english: "the degree program" },
        { german: "der Aushang, --e", english: "the notice board" },
        { german: "der Anhang, --e", english: "the attachment" },
        { german: "der Ausnahmefall, --", english: "the exceptional case" },
        { german: "der Buchhalter, --", english: "the accountant" },
        { german: "der Maschinenbau (nur Sg.)", english: "the mechanical engineering" },
        { german: "der Posten, -", english: "the post" },
        { german: "das Erstsemester, -", english: "the freshman" },
        { german: "das Plädoyer, -s", english: "the plea" },
        { german: "das Studiensekretariat, -e", english: "the student admin. office" },
        { german: "das Anschreiben, -", english: "the cover letter" },
        { german: "das Vorstellungsgespräch", english: "the interview" },
        { german: "das Protokoll", english: "the protocol" },
        { german: "das Stipendium", english: "the scholarship" },
        { german: "das Lehramt", english: "the teaching profession" },
        { german: "effizient", english: "efficient" },
        { german: "konstant", english: "constant" },
        { german: "zulassungsfrei", english: "approval free" },
        { german: "anspruchsvoll", english: "demanding" },
        { german: "EDV-gestützt", english: "IT-supported" },
        { german: "kaufmännisch", english: "commercially" },
        { german: "mittelständisch", english: "medium-sized" },
        { german: "tätig", english: "employed" }
    ],
},

    lektion8: {
        name: "Lektion 8: Health & Medicine",
        cards: [
        // Lektion 8: Health & Medicine
        { german: "ausscheiden + A", english: "to excrete" },
        { german: "entgiften + A", english: "to detoxify" },
        { german: "erbrechen + A", english: "to vomit" },
        { german: "gelangen in + A", english: "to get into" },
        { german: "jucken", english: "to itch" },
        { german: "zu sich nehmen + A", english: "to ingest" },
        { german: "schlucken + A", english: "to swallow" },
        { german: "sich entzünden", english: "to be inflamed" },
        { german: "anlegen + A", english: "to apply" },
        { german: "desinfizieren + A", english: "to disinfect" },
        { german: "infizieren + A", english: "to infect" },
        { german: "versorgen + A", english: "to treat, to care for" },
        { german: "die Atmung (nur Sg.)", english: "the breathing" },
        { german: "die Behinderung, -en", english: "the disability" },
        { german: "die (Harn-)Blase, -n", english: "the (urinary) bladder" },
        { german: "die (Lungen-)Entzündung, -en", english: "the (lung) inflammation" },
        { german: "die Epilepsie (nur Sg.)", english: "the epilepsy" },
        { german: "die (Pilz-)Infektion, -en", english: "the (fungal) infection" },
        { german: "die Leber, -n", english: "the liver" },
        { german: "die Lunge, -n", english: "the lung" },
        { german: "die Chirurgin, -nen", english: "the surgeon" },
        { german: "die Kanüle, -n", english: "the cannula" },
        { german: "die Verdauung (nur Sg.)", english: "the digestion" },
        { german: "die Physiotherapeutin, -nen", english: "the physiotherapy" },
        { german: "die Niere, -n", english: "the kidney" },
        { german: "die Hebamme", english: "the midwife" },
        { german: "die Substanz", english: "the substance" },
        { german: "die Einstichstelle", english: "the injection site" },
        { german: "die (Blut-/Stuhl-/Urin-)Probe, -n", english: "the (blood,stool,urine) sample" },
        { german: "die Sehne, -n", english: "the tendon" },
        { german: "die Psychologin, -nen", english: "the psychologist" },
        { german: "die Röntgenaufnahme, -n", english: "the X-ray" },
        { german: "die Schiene, -n", english: "the splint" },
        { german: "die Stationsleiterin, -nen", english: "the ward manager" },
        { german: "die Vene, -n", english: "the vein" },
        { german: "die Ultraschalluntersuchung, -e", english: "the ultrasound examination" },
        { german: "der Darm, --e", english: "the intestine" },
        { german: "der Urin (nur Sg.)", english: "the urine" },
        { german: "der Durchfall, --e", english: "the diarrhea" },
        { german: "der Schwindel (nur Sg.)", english: "the dizziness" },
        { german: "der Daumen, --", english: "the thumb" },
        { german: "der Pilz, --e", english: "the fungus" },
        { german: "der Ausschlag, --e", english: "the rash" },
        { german: "der Giftstoff, --e", english: "the toxic substance" },
        { german: "der (Knochen-)Bruch, -e", english: "the (bone) fracture" },
        { german: "der Puls (nur Sg.)", english: "the pulse" },
        { german: "der Blutzucker(spiegel), -", english: "the blood sugar (level)" },
        { german: "der Kittel, -", english: "the gown" },
        { german: "der Blutwert, -e", english: "the blood value" },
        { german: "der blaue Fleck, die blauen Flecken", english: "the bruise, bruises" },
        { german: "der Blutdruck (nur Sg.)", english: "the blood pressure" },
        { german: "der Chirurg, -en", english: "the surgeon" },
        { german: "der Physiotherapeut, -en", english: "the physiotherapist" },
        { german: "der Tupfer, -", english: "the swab" },
        { german: "der Seelsorger, -", english: "the counsellor" },
        { german: "der Geburtshelfer, -", english: "the obstetrician" },
        { german: "der Psychologe, -n", english: "the psychologist" },
        { german: "der Stationsleiter, -", english: "the ward manager" },
        { german: "der Wundstarrkrampf (nur Sg.)", english: "the tetanus" },
        { german: "der Katheter", english: "the catheter" },
        { german: "das Symptom, -e", english: "the symptom" },
        { german: "das Ultraschallbild, -er", english: "the ultrasound image" },
        { german: "das Desinfektionsmittel, -", english: "the disinfectant" },
        { german: "das Pflegepersonal (nur Sg.)", english: "the nursing staff" },
        { german: "das Bakterium, Bakterien", english: "the bacterium, bacteria" },
        { german: "das Magnetresonanztomogramm, -e (MRT)", english: "the Magnetic Resonance Imaging (MRI)" },
        { german: "das EKG (Elektrokardiogramm)", english: "the Electrocardiogram (ECG)" },
        { german: "das Untersuchungsergebnis", english: "the examination result" },
        { german: "fieberhaft", english: "feverish" },
        { german: "geistig", english: "mental" },
        { german: "chronisch", english: "chronic" },
        { german: "entzündet", english: "inflamed" },
        { german: "ansprechbar", english: "responsive" },
        { german: "bewusstlos", english: "unconscious" },
        { german: "akut", english: "acute" },
        { german: "ansteckend", english: "contagious" },
        { german: "psychologisch", english: "psychological" },
        { german: "nackt", english: "naked" },
        { german: "neurologisch", english: "neurological" },
        { german: "spezifisch", english: "specific" },
        { german: "nervlich", english: "nervous" },
        { german: "schmerzhaft", english: "painful" },
        { german: "lebensgefährlich", english: "life threatening" },
        { german: "nüchtern", english: "sober" },
        { german: "bohrend", english: "drilling" },
        { german: "stechend", english: "stinging" },
        { german: "brennend", english: "burning" },
        { german: "gutartig", english: "benign" },
        { german: "drückend", english: "pressing" },
        { german: "zuckerkrank", english: "diabetic" },
        { german: "pochend", english: "throbbing" },
        { german: "blass", english: "pale" }
    ],
},
        lektion9: {
        name: "Lektion 9: Technology & Construction",
        cards: [
        // Lektion 9: Technology & Construction
        { german: "befestigen + A", english: "to fix" },
        { german: "entwerfen + A", english: "to design" },
        { german: "fertigen + A", english: "to manufacture" },
        { german: "austauschen + A", english: "to replace" },
        { german: "auswechseln + A", english: "to replace" },
        { german: "instandhalten + A", english: "to keep in good condition" },
        { german: "montieren + A", english: "to mount" },
        { german: "optimieren + A", english: "to optimize" },
        { german: "programmieren + A", english: "to program" },
        { german: "sicherstellen + A", english: "to ensure" },
        { german: "streichen + A", english: "to paint" },
        { german: "tapezieren + A", english: "to wallpaper" },
        { german: "tropfen", english: "to drip" },
        { german: "überwachen + A", english: "to monitor" },
        { german: "verlegen + A", english: "to lay" },
        { german: "warten + A", english: "to service" },
        { german: "einen Strom-Schlag bekommen", english: "to get an electric shock" },
        { german: "abbrechen + A", english: "to terminate/abort" },
        { german: "abstürzen", english: "to crash" },
        { german: "auswerfen + A", english: "to eject" },
        { german: "fehlschlagen", english: "to fail" },
        { german: "setzen auf + A", english: "to put on" },
        { german: "fest verbauen + A", english: "to install firmly" },
        { german: "verschieben + A", english: "to move" },
        { german: "zugreifen auf + A", english: "to access" },
        { german: "die (Software-)Anwendung, -en", english: "the (software) application" },
        { german: "die Elektrikerin, -nen", english: "the electrician" },
        { german: "die Fertigung (nur Sg.)", english: "the manufacture" },
        { german: "die Nutzerfreundlichkeit (nur Sg.)", english: "the user friendliness" },
        { german: "die Schornsteinfegerin, -nen", english: "the chimney sweep" },
        { german: "die Schraube, -n", english: "the screw" },
        { german: "die Sicherung, -en", english: "the fuse" },
        { german: "die Tapete, -n", english: "the wallpaper" },
        { german: "die Drohne, -n", english: "the drone" },
        { german: "die Elektrizität (nur Sg.)", english: "the electricity" },
        { german: "die Fehlermeldung, -en", english: "the error message" },
        { german: "die Feststelltaste, -n", english: "the Caps Lock key" },
        { german: "die Funktion, -en", english: "the function" },
        { german: "die Akku-Kapazität, -en", english: "the battery capacity" },
        { german: "die Ladezeit, -en", english: "the charging time" },
        { german: "die Laufzeit, -en", english: "the running time" },
        { german: "der Schornsteinfeger, -", english: "the chimney sweep" },
        { german: "der/das Thermostat, -e", english: "the thermostat" },
        { german: "der Strom-/Gas-Zähler, -", english: "the electricity/gas meter" },
        { german: "der Zählerstand, --e", english: "the meter reading" },
        { german: "der Befehl, -e", english: "the command" },
        { german: "der E-Roller, E-Scooter", english: "the e-scooter" },
        { german: "der Rahmen, -", english: "the frame" },
        { german: "der Vorgang, --e", english: "the process" },
        { german: "der Flachbildfernseher, -", english: "the flat screen TV" },
        { german: "der Griff, -e", english: "the handle" },
        { german: "der Geschirrspüler, -", english: "the dishwasher" },
        { german: "der Papierkorb, --e", english: "the wastepaper basket" },
        { german: "der Wäschetrockner, -", english: "the tumble dryer" },
        { german: "das Preis-Leistungs-Verhältnis, -se", english: "the price-performance ratio" },
        { german: "die Leistung (nur Sg.)", english: "the performance" },
        { german: "die Wiederherstellung, -en", english: "the restoration" },
        { german: "das Bauteil, -e", english: "the component" },
        { german: "das Gerüst, -e", english: "the scaffolding" },
        { german: "das Gewinde, -", english: "the thread" },
        { german: "das Ventil, -e", english: "the valve" },
        { german: "das Design, -s", english: "the design" },
        { german: "das Display, -s", english: "the display" },
        { german: "das Navi, -s", english: "the navigation system" },
        { german: "das Pedal, -e", english: "the pedal" },
        { german: "altmodisch", english: "old-fashioned" },
        { german: "Design/Preis/Qualität hin oder her", english: "design/price/quality or not" },
        { german: "störungsfrei", english: "free from interference" },
        { german: "bestehend", english: "existing" },
        { german: "austauschbar", english: "replaceable" },
        { german: "einbaubar", english: "installable" },
        { german: "elegant", english: "elegant" },
        { german: "automatisch", english: "automatically" }
    ],
},

    lektion10: {
        name: "Lektion 10: Environment & Ecology",
        cards: [
        // Lektion 10: Environment & Ecology
        { german: "abbauen + A", english: "to abolish, tear down" },
        { german: "abschaffen + A", english: "to abolish" },
        { german: "aufnehmen + A", english: "to absorb" },
        { german: "ausstoßen + A", english: "to emit" },
        { german: "durchbrechen + A", english: "to break through" },
        { german: "einschränken + A", english: "to reduce" },
        { german: "erhalten + A", english: "to preserve" },
        { german: "erzeugen + A", english: "to generate" },
        { german: "freisetzen + A", english: "to release" },
        { german: "gelangen in + A", english: "to get into" },
        { german: "halten + A", english: "to maintain" },
        { german: "überdenken + A", english: "to rethink" },
        { german: "verschwenden + A", english: "to waste" },
        { german: "wiederverwenden + A", english: "to reuse" },
        { german: "zerfallen zu + D", english: "to disintegrate" },
        { german: "ansteigen", english: "to increase" },
        { german: "umwandeln + A in + A", english: "to convert" },
        { german: "sich ausbreiten", english: "to spread" },
        { german: "austreten aus + D", english: "to leak/escape" },
        { german: "reflektieren + A", english: "to reflect" },
        { german: "widerspiegeln + A", english: "to reflect" },
        { german: "schmelzen", english: "to melt" },
        { german: "überschwemmen + A", english: "to flood" },
        { german: "die Emission, -en", english: "the emission" },
        { german: "die Nachhaltigkeit (nur Sg.)", english: "the sustainability" },
        { german: "die Strom-/Energie-Erzeugung (nur Sg.)", english: "the electricity/energy generation" },
        { german: "die Radioaktivität (nur Sg.)", english: "the radio activity" },
        { german: "die Kohle (nur Sg.)", english: "the coal" },
        { german: "die Ressource, -n", english: "the resource" },
        { german: "die Massentierhaltung (nur Sg.)", english: "the factory farming" },
        { german: "die Verkehrswende, -n", english: "the transport transition" },
        { german: "die Umstellung von + D auf + A", english: "the change over from to" },
        { german: "die Hülle, -n", english: "the cover" },
        { german: "die Auswirkung, -en", english: "the effect" },
        { german: "die Schicht, -en", english: "the layer" },
        { german: "die Erd-Atmosphäre, -n", english: "the earth's atmosphere" },
        { german: "die Überschwemmung, -en", english: "the flood" },
        { german: "die Dürre", english: "the drought" },
        { german: "die Traufe", english: "the eaves" },
        { german: "der Ausbau (nur Sg.)", english: "the expansion" },
        { german: "der Nahrungs-Kreislauf", english: "the food cycle" },
        { german: "der Ausstoß (nur Sg.)", english: "the output" },
        { german: "der Lebensraum, -e", english: "the habitat" },
        { german: "der ökologische Fußabdruck, -e", english: "the ecological footprint" },
        { german: "der Lebensstandard (nur Sg.)", english: "the living standard" },
        { german: "der Kohleausstieg (nur Sg.)", english: "the coal phase-out" },
        { german: "der Nährstoff, -e", english: "the nutrient" },
        { german: "der ÖPNV (öffentlicher Personennahverkehr)", english: "the local public transport" },
        { german: "der Rückgang, --e", english: "the decline" },
        { german: "der Kunststoff-Partikel, --", english: "the plastic particle" },
        { german: "der Rückstand, --e", english: "the residue" },
        { german: "der Regenwald, --er", english: "the rainforest" },
        { german: "der Gift-/Schad-Stoff, --e", english: "the poisonous/harmful substance" },
        { german: "der Rohstoff, --e", english: "the raw material" },
        { german: "der Wasser-Dampf, --e", english: "the water steam" },
        { german: "der Treibhaus-Effekt, -e", english: "the greenhouse effect" },
        { german: "der Meeres-/Wasser-Spiegel, -", english: "the sea/water level" },
        { german: "der Gletscher, -", english: "the glacier" },
        { german: "der Sonnen-Strahl, -en", english: "the sun ray" },
        { german: "der Klimawandel", english: "the climate change" },
        { german: "die Erderwärmung (nur Sg.)", english: "the global warming" },
        { german: "der Anteil", english: "the share" },
        { german: "der Sauerstoff = O2", english: "the oxygen = O2" },
        { german: "der Verbrennungsmotor", english: "the internal combustion engine" },
        { german: "das Artensterben (nur Sg.)", english: "the extinction of species" },
        { german: "das Mikroplastik (nur Sg.)", english: "the microplastic" },
        { german: "das Einwegplastik (nur Sg.)", english: "the single use plastic" },
        { german: "das Transport-/Verkehrs-Wesen", english: "the transport system" },
        { german: "das Elektrofahrzeug, -e", english: "the electric vehicle" },
        { german: "das Wegwerfprodukt, -e", english: "the disposable product" },
        { german: "das Kohlenstoffdioxid = CO2", english: "the carbon dioxide = CO2" },
        { german: "das Hochwasser (nur Sg.)", english: "the flood" },
        { german: "das Methan (nur Sg.)", english: "the methane" },
        { german: "das Treib-/Glashaus, --er", english: "the greenhouse/glass house" },
        { german: "das Ökosystem", english: "the ecosystem" },
        { german: "das Element", english: "the element" },
        { german: "die Abholzung, -en", english: "the deforestation" },
        { german: "die Ausbeutung (nur Sg.)", english: "the exploitation" },
        { german: "die Artenvielfalt (nur Sg.)", english: "the biodiversity" },
        { german: "die Elektromobilität (nur Sg.)", english: "the electromobility" },
        { german: "biologisch abbaubar", english: "biological degradable" },
        { german: "nachhaltig", english: "sustainable" },
        { german: "gasförmig", english: "gaseous" },
        { german: "lebenswichtig", english: "vital" },
        { german: "irreparabel", english: "irreparable" },
        { german: "organisch", english: "organic" },
        { german: "kontaminiert", english: "contaminated" },
        { german: "ökologisch", english: "ecological" }
    ],
},

    lektion11: {
        name: "Lektion 11: Science & Research",
        cards: [
        // Lektion 11: Science & Research
        { german: "ausgehen von + D", english: "to assume" },
        { german: "auseinandergehen", english: "to not be same" },
        { german: "auswerten + A", english: "to evaluate" },
        { german: "sich befassen mit + D", english: "to deal with" },
        { german: "berücksichtigen + A", english: "to consider" },
        { german: "definieren + A", english: "to define" },
        { german: "durchführen + A", english: "to conduct" },
        { german: "eingehen auf + A", english: "to respond to" },
        { german: "erheben + A", english: "to gather, collect" },
        { german: "sich erschließen + D", english: "to open up" },
        { german: "formulieren + A", english: "to formulate" },
        { german: "übereinstimmen mit + D", english: "to agree with" },
        { german: "veranschaulichen + A", english: "to illustrate" },
        { german: "widerlegen + A", english: "to refute" },
        { german: "zitieren + A", english: "to cite" },
        { german: "sich aufladen", english: "to charge electrically" },
        { german: "aufstellen + A", english: "to set up" },
        { german: "bestehen in + D", english: "to consist in" },
        { german: "sich entladen", english: "to discharge" },
        { german: "erforschen + A", english: "to research" },
        { german: "kondensieren", english: "to condense" },
        { german: "sich lösen in + D", english: "to dissolve" },
        { german: "reiben mit + D", english: "to rub with" },
        { german: "strahlen", english: "to radiate" },
        { german: "auf den Punkt bringen + A", english: "to get to the point" },
        { german: "sich aus dem Kontext erschließen", english: "to infer from the context" },
        { german: "einen Gedanken zu Ende führen", english: "to finish a thought" },
        { german: "einen Vortrag halten über + A", english: "to give a lecture about" },
        { german: "zum Ende kommen", english: "to come to the end" },
        { german: "zu anderen/denselben Ergebnissen kommen", english: "to come to different/same results" },
        { german: "aus dem Konzept kommen", english: "to get out of the concept" },
        { german: "Bezug nehmen auf + A", english: "to refer to" },
        { german: "im Widerspruch stehen zu + D", english: "to contradict to" },
        { german: "eine Ansicht teilen", english: "to share a view" },
        { german: "eine Aussage treffen zu + D", english: "to make a statement about" },
        { german: "einen Eindruck vermitteln", english: "to give an impression" },
        { german: "die Auffassung, -en", english: "the view, opinion" },
        { german: "die Befragung, -en", english: "the survey" },
        { german: "die Behauptung, -en", english: "the claim" },
        { german: "die Prognose, -n", english: "the prognosis" },
        { german: "die Zimmertemperatur, -en", english: "the room temperature" },
        { german: "die Schwerkraft (nur Sg.)", english: "the gravity" },
        { german: "die These, -n", english: "the thesis" },
        { german: "die Tagung, -en", english: "the conference" },
        { german: "die Vorhersage, -n", english: "the prediction" },
        { german: "die Anziehungskraft, --e", english: "the gravitational pull" },
        { german: "die chemische Bindung, -en", english: "the chemical bond" },
        { german: "die Eigenschaft, -en", english: "the property" },
        { german: "die Gesetzmäßigkeit, -en", english: "the lawfulness" },
        { german: "die Lehre, -n", english: "the science" },
        { german: "die Masse, -n", english: "the mass" },
        { german: "die Materie (nur Sg.)", english: "the matter" },
        { german: "die Oberfläche, -n", english: "the surface" },
        { german: "die Rasse, -n", english: "the breed" },
        { german: "die elektrische Spannung, -en", english: "the electrical voltage" },
        { german: "die Substanz, -en", english: "the substance" },
        { german: "die Umwandlung, -en", english: "the conversion" },
        { german: "die Vererbung (nur Sg.)", english: "the hereditary, inheritance" },
        { german: "die Wechselwirkung, -en", english: "the interaction" },
        { german: "die Zelle, -n", english: "the cell" },
        { german: "der Grundsatz, -e", english: "the principle" },
        { german: "der Proband, -en; die Probandin, -nen", english: "the test subject" },
        { german: "der Atomkern, -e", english: "the atomic nucleus" },
        { german: "der Dackel, -", english: "the dachshund" },
        { german: "der Schäferhund, -e", english: "the sheep dog" },
        { german: "der chemische Stoff, -e", english: "the chemical substance" },
        { german: "das Prinzip, Prinzipien", english: "the principle" },
        { german: "das Experiment, -e", english: "the experiment" },
        { german: "das Atom, -e", english: "the atom" },
        { german: "das Eisen (nur Sg.)", english: "the iron" },
        { german: "das Element, -e", english: "the element" },
        { german: "das Lebewesen, -", english: "the living thing" },
        { german: "das Gewebe, -", english: "the tissue" },
        { german: "das Molekül, -e", english: "the molecule" }
    ],
},

    lektion12: {
        name: "Lektion 12: Society & Equality",
        cards: [
        // Lektion 12: Society & Equality
        { german: "abbauen + A", english: "to break down" },
        { german: "aufbauen + A", english: "to build" },
        { german: "ausgrenzen + A", english: "to ostracize" },
        { german: "ausschließen + A", english: "to exclude" },
        { german: "benachteiligen + A", english: "to disadvantage" },
        { german: "demonstrieren für/gegen + A", english: "to demonstrate" },
        { german: "einbeziehen + A", english: "to include" },
        { german: "einhalten + A", english: "to comply" },
        { german: "eintreten für + A", english: "to stand up for" },
        { german: "missachten + A", english: "to disregard" },
        { german: "teilhaben an + D", english: "to partake in" },
        { german: "tolerieren + A", english: "to tolerate" },
        { german: "verkünden + A", english: "to proclaim" },
        { german: "verstoßen gegen + A", english: "to violate, to infringe" },
        { german: "die Brüderlichkeit (nur Sg.)", english: "the brotherhood" },
        { german: "die Diskriminierung, -en", english: "the discrimination" },
        { german: "die Behinderten-/Frauen-/Fremden-/Islam-Feindlichkeit (nur Sg.)", english: "the disability/women/strangers/Islam hostility" },
        { german: "die Gleichheit (nur Sg.)", english: "the equality" },
        { german: "die Hautfarbe, -n", english: "the skin color" },
        { german: "die Homophobie (nur Sg.)", english: "the homophobia" },
        { german: "die gesellschaftliche Klasse, -n", english: "the social class" },
        { german: "die Nächstenliebe (nur Sg.)", english: "the charity" },
        { german: "die gesellschaftliche Schicht, -en", english: "the social class" },
        { german: "die Solidarität (nur Sg.)", english: "the solidarity" },
        { german: "die Vernunft (nur Sg.)", english: "the reason" },
        { german: "die Würde (nur Sg.)", english: "the dignity" },
        { german: "die Alterspyramide, -n", english: "the age pyramid" },
        { german: "die Altersstruktur, -en", english: "the age structure" },
        { german: "die Armut (nur Sg.)", english: "the poverty" },
        { german: "die Bildung (nur Sg.)", english: "the education" },
        { german: "die Geburtenrate, -n", english: "the birth rate" },
        { german: "die Lebenserwartung (nur Sg.)", english: "the life expectancy" },
        { german: "die Nachbarschaft, -en", english: "the neighborhood" },
        { german: "die Ressource, -n", english: "the resource" },
        { german: "die Ober-/Mittel-/Unterschicht, -en", english: "the upper/middle/lower class" },
        { german: "die Soziologie (nur Sg.)", english: "the sociology" },
        { german: "die Sterblichkeit (nur Sg.)", english: "the mortality" },
        { german: "die gesellschaftliche Teilhabe (nur Sg.)", english: "the social participation" },
        { german: "die soziale Ungleichheit, -en", english: "the social inequality" },
        { german: "die Ungleichverteilung, -en", english: "the unequal distribution" },
        { german: "die Muslimin, -nen", english: "the Muslim woman" },
        { german: "die Verteilung, -en", english: "the distribution" },
        { german: "das Vermögen", english: "the asset" },
        { german: "das Handicap, -s", english: "the handicap" },
        { german: "das Ansehen (nur Sg.)", english: "the prestige" },
        { german: "das Wachstum (nur Sg.)", english: "the growth" },
        { german: "der Geist, -er", english: "the spirit" },
        { german: "der Besitz (nur Sg.)", english: "the possession" },
        { german: "der Jude, -n; die Jüdin, -nen", english: "the jew" },
        { german: "der Muslim, -e", english: "the Muslim" },
        { german: "der Rassismus (nur Sg.)", english: "the racism" },
        { german: "der gesellschaftliche Stand, --e", english: "the social status" },
        { german: "der Abstand, --e", english: "the distance" },
        { german: "der Begriff, -e", english: "the term" },
        { german: "der Industriestaat, -en", english: "the industrial state" },
        { german: "der Rückgang, --e", english: "the decline" },
        { german: "der gute/schlechte Ruf (nur Sg.)", english: "the good/bad reputation" },
        { german: "der Stadtrand, --er", english: "the suburb" },
        { german: "der Wohlstand (nur Sg.)", english: "the prosperity" },
        { german: "der Besser-/Gering-Verdienende, -", english: "the higher/lower earner" },
        { german: "das Eigentum (nur Sg.)", english: "the property" },
        { german: "das Menschenrecht, -e", english: "the human right" },
        { german: "barrierefrei", english: "barrier-free" },
        { german: "begabt", english: "gifted" },
        { german: "materiell", english: "material" },
        { german: "sonstig", english: "other" },
        { german: "moderat", english: "moderate" },
        { german: "rasant", english: "rapidly" },
        { german: "drastisch", english: "drastic" },
        { german: "absolut", english: "absolute" }
    ],
},

    lektion13: {
        name: "Lektion 13: Law & Administration",
        cards: [
        // Lektion 13: Law & Administration
        { german: "bewilligen + A", english: "to approve" },
        { german: "vorsprechen bei + D", english: "to appear" },
        { german: "erlischen", english: "to lapse/expire" },
        { german: "freistellen von + D", english: "to excuse from" },
        { german: "kalkulieren + A", english: "to calculate" },
        { german: "mitwirken an + D", english: "to be involved" },
        { german: "nachkommen + D", english: "to fulfill" },
        { german: "stattgeben + D", english: "to grant/sustain" },
        { german: "anfallen", english: "to attack" },
        { german: "anklagen + A", english: "to charge" },
        { german: "aussagen", english: "to testify" },
        { german: "beschuldigen + A", english: "to accuse" },
        { german: "betragen", english: "to amount to" },
        { german: "eingehen", english: "to come in/arrive" },
        { german: "die Anpassung, -en", english: "the customization" },
        { german: "die Basis, Basen", english: "the base, bases" },
        { german: "die Entschädigung, -en", english: "the compensation" },
        { german: "die Eingangsbestätigung, -en", english: "the confirmation of receipt" },
        { german: "die Inanspruchnahme, -n", english: "the utilization" },
        { german: "die Mitwirkungspflicht (nur Sg.)", english: "the obligation to cooperate" },
        { german: "die Gesetzes-Grundlage, -n", english: "the legal basis" },
        { german: "der Erhalt (nur Sg.)", english: "the receipt" },
        { german: "die Polizeidirektion, -en", english: "the police department" },
        { german: "die Rentenversicherung, -en", english: "the pension insurance" },
        { german: "die Rückzahlungsverpflichtung, -en", english: "the repayment obligation" },
        { german: "die Rechtsbehelfsbelehrung, -en", english: "the information on legal remedies" },
        { german: "die Bekanntgabe, -n", english: "the announcement" },
        { german: "die Verjährungsfrist, -en", english: "the period of limitation" },
        { german: "die Abschiebung, -en", english: "the deportation" },
        { german: "die Gerichtsverhandlung, -en", english: "the court hearing" },
        { german: "die Geringfügigkeit, -en", english: "the insignificance" },
        { german: "die Straftat, -en", english: "the offence" },
        { german: "die Straßenverkehrsordnung, -en", english: "the road traffic regulations" },
        { german: "das Verwaltungsgericht, -e", english: "the administrative court" },
        { german: "der Staatsanwalt, -e; die Staatsanwältin, -nen", english: "the public prosecutor" },
        { german: "der Verstoß, -e", english: "the infringement" },
        { german: "der Verteidiger, -; die Verteidigerin, -nen", english: "the defender" },
        { german: "der Beitrag", english: "the contribution" },
        { german: "der Nachweis, -e", english: "the proof" },
        { german: "der Schadensersatzanspruch, -e", english: "the claim for damages" },
        { german: "der Zahlungseingang, -e", english: "the receipt of payment" },
        { german: "der/die Angeklagte, -n", english: "the accused" },
        { german: "der Antragsteller, -; die Antragstellerin, -nen", english: "the claimant" },
        { german: "der Ankläger, -; die Anklägerin, -nen", english: "the accuser" },
        { german: "der Gerichtsdieners, -; die Gerichtsdienersin, -nen", english: "the bailiff" },
        { german: "der Gerichtssaal, -e", english: "the courtroom" },
        { german: "offensichtlich", english: "obviously" },
        { german: "hiermit", english: "with this" },
        { german: "unbegründet", english: "unjustified" },
        { german: "i.A. (im Auftrag)", english: "on behalf of" },
        { german: "fristgemäß = fristgerecht", english: "in due time" },
        { german: "personenbezogen", english: "personal" },
        { german: "umgehend", english: "immediately" },
        { german: "auf Antrag", english: "upon request" },
        { german: "vor Ablauf", english: "before expiry" },
        { german: "seitens", english: "on the part of" },
        { german: "von Unbekannt", english: "from unknown" },
        { german: "zur Niederschrift", english: "for the record" },
        { german: "geständig", english: "confessed" },
        { german: "unter Ausschluss der Öffentlichkeit", english: "without the public" },
        { german: "schuldfähig", english: "culpable" },
        { german: "vorbestraft", english: "previously convicted" },
        { german: "einen Beruf ausüben", english: "to pursue a profession" },
        { german: "eine Pflicht erfüllen", english: "to fulfill a duty" },
        { german: "Auskunft erteilen + D", english: "to give information" },
        { german: "zustande kommen", english: "to come about" },
        { german: "zugrunde liegen + D", english: "to underlie" },
        { german: "in Kenntnis setzen über etwas", english: "to inform about something" },
        { german: "eine Frist einhalten", english: "to meet a deadline" },
        { german: "Widerspruch einlegen gegen + A", english: "to object to" },
        { german: "ein Gerichts-/Straf-Verfahren einleiten", english: "to initiate legal/criminal proceedings" },
        { german: "Klage einreichen", english: "to file a lawsuit" },
        { german: "ein Gerichts-Verfahren eröffnen", english: "to initiate court proceedings" },
        { german: "ein Urteil fällen", english: "to pass a judgement" },
        { german: "eine Anklage fallen lassen", english: "to drop a charge" },
        { german: "Kosten tragen", english: "to bear costs" },
        { german: "die Anklage/die Verteidigung vertreten", english: "to represent the prosecution/defense" },
        { german: "eine Anklage zurückziehen", english: "to withdraw a charge" }
    ]
},
            
},
 // ========== PLACEHOLDERS FOR FUTURE LEVELS ========== //
    c1: {
        name: "C1 - Advanced",
        lessons: {}
    },
    
    c2: {
        name: "C2 - Mastery", 
        lessons: {}
    }
}
};